export  const LGA = 
  
{State_Office: [{value:  'State Office' , name: 'State Office'}],
Abi: [{value:  'Eja Memorial Hospital' , name: 'Eja Memorial Hospital'},
         {value:  'Igbo-Imabana Model Primary Health Centre' , name: 'Igbo-Imabana Model Primary Health Centre'}
        ],
 Akamkpa: [{value:  'Akamkpa General Hospital' , name: 'Akamkpa General Hospital'},
         {value:  'Aningeje Primary Health Centre' , name: 'Aningeje Primary Health Centre'},
         {value:  'Mfamosing Primary Health Center' , name: 'Mfamosing Primary Health Center'},
         {value:  'Mma Efa Health Centre' , name: 'Mma Efa Health Centre'},
         {value:  'Oban Health Centre' , name: 'Oban Health Centre'}
        ],
 Akpabuyo: [{value:  'Akpabuyo St Joseph Hospital' , name: 'Akpabuyo St Joseph Hospital'},
         {value:  'Ikot Edem Odo Health Centre' , name: 'Ikot Edem Odo Health Centre'}
        ],
 Bakassi: [{value:  'Ekpri Obutong Health Centre' , name: 'Ekpri Obutong Health Centre'},
         {value:  'Ikang Primary Health Centre' , name: 'Ikang Primary Health Centre'}
        ],
 Biase: [{value:  'Akpet Central Cottage Hospital' , name: 'Akpet Central Cottage Hospital'},
         {value:  'Aya Medical Centre' , name: 'Aya Medical Centre'}
        ],
 Boki: [{value:  'Katchuan Irruan Model PHC' , name: 'Katchuan Irruan Model PHC'},
         {value:  'Okundi Comprehensive Health Centre' , name: 'Okundi Comprehensive Health Centre'}
        ],
 Calabar_Municipal: [{value:  'Bakor Medical centre' , name: 'Bakor Medical centre'},
         {value:  'Calabar General Hospital' , name: 'Calabar General Hospital'},
         {value:  'Calabar Women and Children Hospital' , name: 'Calabar Women and Children Hospital'},
         {value:  'Diamond Hill Health Centre' , name: 'Diamond Hill Health Centre'},
         {value:  'Ekorinim Health Centre' , name: 'Ekorinim Health Centre'},
         {value:  'Emmanuel Infirmiry' , name: 'Emmanuel Infirmiry'},
         {value:  'Faith Foundation Clinic' , name: 'Faith Foundation Clinic'},
         {value:  'Hiltop Healthcare Foundation' , name: 'Hiltop Healthcare Foundation'},
         {value:  'Ikot Ekpo Health Centre (Ward 10)' , name: 'Ikot Ekpo Health Centre (Ward 10)'},
         {value:  'Ikot Enebong Health Post' , name: 'Ikot Enebong Health Post'},
         {value:  'Ishie Health Post' , name: 'Ishie Health Post'},
         {value:  'Kasuk Health Centre' , name: 'Kasuk Health Centre'},
         {value:  'Nyahasang Health Centre' , name: 'Nyahasang Health Centre'},
         {value:  'Police Hospital' , name: 'Police Hospital'},
         {value:  'University of Calabar Medical Centre' , name: 'University of Calabar Medical Centre'},
         {value:  'University of Calabar Teaching Hospital' , name: 'University of Calabar Teaching Hospital'}
        ],
 Calabar_South: [{value:  'Akani Esuk Health Centre' , name: 'Akani Esuk Health Centre'},
         {value:  'Anderson Primary Health Centre' , name: 'Anderson Primary Health Centre'},
         {value:  'Calabar South Family Health Centre' , name: 'Calabar South Family Health Centre'},
         {value:  'Dr Lawrence Henshaw Memorial Hospital' , name: 'Dr Lawrence Henshaw Memorial Hospital'},
         {value:  'Ekpo Abasi Primary Health Centre' , name: 'Ekpo Abasi Primary Health Centre'},
         {value:  'Essierebom Primary Health Centre' , name: 'Essierebom Primary Health Centre'},
         {value:  'Henshaw Town Health Post' , name: 'Henshaw Town Health Post'},
         {value:  'Mambo Clinic' , name: 'Mambo Clinic'},
         {value:  'Mount Zion Medical Centre' , name: 'Mount Zion Medical Centre'},
         {value:  'Goldie Clinic' , name: 'Goldie Clinic'},
         {value:  'Cross River University of Science and Technology (CRUTECH) Medical Centre' , name: 'Cross River University of Science and Technology (CRUTECH) Medical Centre'},
         {value:  'Peace medical centre' , name: 'Peace medical centre'},
         {value:  'Anantigha Primary Health Centre' , name: 'Anantigha Primary Health Centre'}
        ],
 Ikom: [{value:  'Holy Family Catholic Hospital' , name: 'Holy Family Catholic Hospital'},
         {value:  'County Specialist Hospital' , name: 'County Specialist Hospital'},
         {value:  'Melrose Hospital' , name: 'Melrose Hospital'}
        ],
 Obubra: [{value:  'Ekana Medical Centre' , name: 'Ekana Medical Centre'},
         {value:  'Obubra General Hospital' , name: 'Obubra General Hospital'},
         {value:  'Obubra Maternal and Child Health Clinic' , name: 'Obubra Maternal and Child Health Clinic'}
        ],
 Odukpani: [{value:  'Ikot Effiong Otop Comprehensive Health Centre (UCTH Annex)' , name: 'Ikot Effiong Otop Comprehensive Health Centre (UCTH Annex)'},
         {value:  'Ukpem General Hospital' , name: 'Ukpem General Hospital'}
        ],
 Yakurr: [{value:  'Ugep General Hospital' , name: 'Ugep General Hospital'}],
  explain :[{ value: 'Not Currently in my Station', name: 'Not Currently in my Station' }]
      
    }

export const  facility_location ={
    'Akamkpa General Hospital': { latitude: '5.32685', longitude: '8.34431' },
    'Akani Esuk Health Centre': { latitude: '4.92907', longitude: '8.31324' },
    'Akpabuyo St Joseph Hospital': { latitude: '4.91587', longitude: '8.4676' },
    'Anantigha Primary Health Centre': { latitude: '4.91754', longitude: '8.32065' },
    'Anderson Primary Health Centre': { latitude: '4.95761', longitude: '8.31228' },
    'Aningeje Primary Health Centre': { latitude: '5.11394', longitude: '8.52556' },
    'Bakor Medical centre': { latitude: '5.0273', longitude: '8.3335' },
    'Calabar General Hospital': { latitude: '4.95366', longitude: '8.33661' },
    'Calabar South Family Health Centre': { latitude: '4.96449', longitude: '8.32306' },
    'Calabar Women and Children Hospital': { latitude: '5.03528', longitude: '8.34722' },
    'Cross River University of Science and Technology (CRUTECH) Medical Centre': { latitude: '4.92789', longitude: '8.33017' },
    'Diamond Hill Health Centre': { latitude: '4.983', longitude: '8.3291' },
    'Dr Lawrence Henshaw Memorial Hospital': { latitude: '4.94901', longitude: '8.3179' },
    'Ekorinim Health Centre': { latitude: '4.99756', longitude: '8.32204' },
    'Ekpo Abasi Primary Health Centre': { latitude: '4.93709', longitude: '8.32587' },
    'Ekpri Obutong Health Centre': { latitude: '4.83039', longitude: '8.51758' },
    'Emmanuel Infirmiry': { latitude: '5.03457', longitude: '8.35074' },
    'Essierebom Primary Health Centre': { latitude: '4.9512', longitude: '8.31018' },
    'Faith Foundation Clinic': { latitude: '5.2132', longitude: '8.3325' },
    'Goldie Clinic': { latitude: '4.98103', longitude: '8.34009' },
    'Henshaw Town Health Post': { latitude: '4.95185', longitude: '8.31674' },
    'Hiltop Health care Foundation': { latitude: '4.99393', longitude: '8.34731' },
    'Ikang Primary Health Centre': { latitude: '4.79593', longitude: '8.52516' },
    'Ikot Edem Odo Health Centre': { latitude: '4.9448', longitude: '8.4442' },
    'Ikot Effiong Otop Comprehensive Health Centre (UCTH Annex)': { latitude: '5.16161', longitude: '8.182' },
    'Ikot Ekpo Health Centre (Ward 10)': { latitude: '5.7798', longitude: '8.3465' },
    'Ikot Enebong Health Post': { latitude: '5.05257', longitude: '8.36123' },
    'Ishie Health Post': { latitude: '4.9921', longitude: '8.3384' },
    'Kasuk Health Centre': { latitude: '5.0275', longitude: '8.3398' },
    'Mambo Clinic': { latitude: '4.94419', longitude: '8.3289' },
    'Mfamosing Primary Health Center': { latitude: '5.10997', longitude: '8.5255' },
    'Mma Efa Health Centre': { latitude: '5.30515', longitude: '8.35679' },
    'Mount Zion Medical Centre': { latitude: '4.93431', longitude: '8.32753' },
    'Nyahasang Health Centre': { latitude: '4.97754', longitude: '8.36368' },
    'Oban Health Centre': { latitude: '5.3138', longitude: '8.5809' },
    'Peace medical centre': { latitude: '4.95679', longitude: '8.31611' },
    'Police Hospital': { latitude: '4.9637', longitude: '8.33193' },
    'Ukem General Hospital': { latitude: '5.07323', longitude: '8.21856' },
    'University of Calabar Medical Centre': { latitude: '4.95482', longitude: '8.34184' },
    'University of Calabar Teaching Hospital': { latitude: '4.9584', longitude: '8.34746' },
    'State Office': { latitude: '4.98577', longitude: '8.34634' }
  }